### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by xjtuqihan** [sadmankiba/FlexBSO#1]
Hello author, I would like to know what are the packages you introduced in your code, pack. h and utils.h. I couldn't find it under doca's lib and include. When I was making your code![屏幕截图 2024-12-11 210047](https://github.com/user-attachments/assets/b91b1450-0cf0-4a92-b42f-5edac357078f)It returned that It couldn't find these two packages.

**Comment by sadmankiba** [comment]
Hi @xjtuqihan , I am afraid I do not remember exactly the packages and versions used. What I can suggest is you can comment out the headers that you do not have. Then, if the compiler does not find a function definition, try to find that function in your installed Doca version.

**Comment by xjtuqihan** [comment]
Ok. Thank you
